apiVersion: batch/v1
kind: Job
metadata:
  name: skirt-batch-job
  namespace: sdsu-rosen-astro-group 
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: skirt-runner
        image: ghcr.io/sdsu-research-ci/astro-notebook@sha256:b790987333dac51a8ea777988bc4bf2b5a09f823819b1419beff51f69075b462
        command: ["/bin/bash", "-c"]
        args: 
          - |
            echo "Initializing Batch Pipeline..."

            git clone https://github.com/AislingA/S2S.git /workspace/S2S
            cd /workspace/S2S
            
            SNAPSHOTS=(150 200 250 296)
            
            for snap in "${SNAPSHOTS[@]}"; do
              echo "Processing snapshot_${snap}.hdf5"
              OUT_DIR="/data/outputs/snapshot_${SNAP}"
              mkdir -p "${OUT_DIR}"

              python src/runner/run_sim.py \
                --input "s3:sdsu-rosen/snapshot_${SNAP}.hdf5" \
                --output-dir "${OUT_DIR}"

              echo "Completed snapshot_${SNAP}"
            done
            
            echo "All 4 simulations complete!"
            
        resources:
          limits:
            memory: "128Gi"
            cpu: "16"
          requests:
            memory: "128Gi"
            cpu: "16"
        volumeMounts:
        - name: s2s-storage
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: s2s-storage
        persistentVolumeClaim:
          claimName: s2s
  backoffLimit: 0