# src/visualization/image_processing.py

import numpy as np
from astropy.convolution import convolve, Gaussian2DKernel
import warnings

def apply_psf(rgb_cube, fwhm_pixels=2.1, instrument="optical_uv"):
    """
    Convolves the raw physical flux arrays with a Point Spread Function (PSF).
    
    Parameters
    ----------
    rgb_cube: numpy.ndarray
        The (3, Y, X) raw data array loaded from fits_loader.py.
    fwhm_pixels: float, optional
        The Full Width at Half Maximum of the PSF in pixels. Default is 2.1.
    instrument: str, optional
        The instrument being simulated. Defaults to "optical_uv".

    Returns
    -------
    convolved_cube: numpy.ndarray
        A (3, Y, X) array where each channel has been spatially smoothed.
    """
    # Convert FWHM to Standard Deviation (Sigma)
    # FWHM = 2 * sqrt(2 * ln(2)) * sigma ≈ 2.3548 * sigma
    sigma = fwhm_pixels / 2.35482
    
    # Create the Gaussian Kernel
    # NOTE FOR JWST: While a Gaussian is perfectly accurate for reproducing the paper's HST 
    # methodology, JWST has a highly complex, diffraction-limited, hexagonal PSF. 
    # For a fully rigorous JWST mock in the future, you would replace this Gaussian2DKernel 
    # with a kernel generated by the `webbpsf` Python package. For now, a Gaussian is a 
    # safe, lightweight approximation.
    kernel = Gaussian2DKernel(x_stddev=sigma)
    
    # Create an empty array to store the smoothed data
    convolved_cube = np.zeros_like(rgb_cube)
    
    # Convolve each color channel independently
    print(f"Applying PSF convolution (FWHM={fwhm_pixels}px) for {instrument}...")
    for i in range(3):
        # We suppress astropy warnings about NaNs if your SKIRT grid has empty edges
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            convolved_cube[i] = convolve(rgb_cube[i], kernel, normalize_kernel=True)
            
    return convolved_cube

def apply_log_stretch(rgb_cube, stretch_factor=1000):
    """
    Applies a non-linear logarithmic stretch to compress the massive dynamic 
    range of astrophysical fluxes into a visible RGB image.

    Parameters
    ----------
    rgb_cube: numpy.ndarray
        The (3, Y, X) array containing the convolved physical fluxes.
    stretch_factor: float, optional
        Controls the aggressiveness of the stretch. Higher numbers pull up 
        fainter background structures more.

    Returns
    -------
    rgb_image: numpy.ndarray
        A (Y, X, 3) array normalized between 0.0 and 1.0, ready for plotting.
    """
    print(f"Applying logarithmic stretch (Factor={stretch_factor})...")
    
    # Isolate the data and remove any negative noise values
    cube_clean = np.clip(rgb_cube, 0, None)
    
    # Global Normalization
    global_max = np.max(cube_clean)
    if global_max > 0:
        cube_normalized = cube_clean / global_max
    else:
        cube_normalized = cube_clean
        
    # The Logarithmic Transformation
    # scaled = log(1 + a * image) / log(1 + a)
    # This prevents values from dropping to negative infinity at 0 flux.
    stretched_cube = np.log10(1 + stretch_factor * cube_normalized) / np.log10(1 + stretch_factor)
    
    # Reorder Axes for Matplotlib
    rgb_image = np.moveaxis(stretched_cube, 0, -1)
    
    # Final safety clip to ensure standard RGB bounds [0.0, 1.0]
    return np.clip(rgb_image, 0, 1)